using System;

namespace BlueStacks.Common
{
	public enum DataManagerCodes
	{
		SUCCESS,
		DEFAULT = -1,
		CANCEL = -2,
		NO_PATH_CHOSEN = -3,
		BACKUP_CANCELLED_DURING_PROCESS = -4,
		ERROR_IN_CREATING_BACKUP_INVALID_PATH_SELECTED = -5,
		ERROR_IN_CREATING_USERINFO_FILE_WHILE_BACKUP = -6,
		EXCEPTION_IN_BACKUP = -7,
		WRONG_PATH_CHOSEN = -8,
		INVALID_OEM = -9,
		INSUFFICIENT_DISK_SPACE = -10,
		EXIT_AS_BACKUP_VERSION_IS_HIGHER_THAN_CURRENT = -11,
		USER_CANCELLED_DUE_TO_CFG_FILE = -12,
		ERROR_IN_MOVING_EXISTING_DATA_TO_TEMP = -13,
		BACKUP_INFO_FILE_NOT_EXIST = -14,
		ERROR_IN_CHANGING_CONFIGURATION_FILES = -15,
		EXIT_AS_USERINFO_FILE_MISSING_IN_BACKUP = -16,
		EXCEPTION_IN_RESTORE = -17,
		BACKUP_FROM_KK_BUILD = -18,
		BACKUP_VERSION_GREATER_THAN_CURRENT_BUILD_VERSION = -19,
		USER_CANCELLED_ON_RESTORE_WARNING = -20
	}
}


