using System;

namespace BlueStacks.Common
{
	public enum GuestApkInstallFailCodes
	{
		INSTALL_FAILED_ALREADY_EXISTS = -1,
		INSTALL_FAILED_INVALID_APK = -2,
		INSTALL_FAILED_INVALID_URI = -3,
		INSTALL_FAILED_INSUFFICIENT_STORAGE = -4,
		INSTALL_FAILED_DUPLICATE_PACKAGE = -5,
		INSTALL_FAILED_NO_SHARED_USER = -6,
		INSTALL_FAILED_UPDATE_INCOMPATIBLE = -7,
		INSTALL_FAILED_SHARED_USER_INCOMPATIBLE = -8,
		INSTALL_FAILED_MISSING_SHARED_LIBRARY = -9,
		INSTALL_FAILED_REPLACE_COULDNT_DELETE = -10,
		INSTALL_FAILED_DEXOPT = -11,
		INSTALL_FAILED_OLDER_SDK = -12,
		INSTALL_FAILED_CONFLICTING_PROVIDER = -13,
		INSTALL_FAILED_NEWER_SDK = -14,
		INSTALL_FAILED_TEST_ONLY = -15,
		INSTALL_FAILED_CPU_ABI_INCOMPATIBLE = -16,
		INSTALL_FAILED_MISSING_FEATURE = -17,
		INSTALL_FAILED_CONTAINER_ERROR = -18,
		INSTALL_FAILED_INVALID_INSTALL_LOCATION = -19,
		INSTALL_FAILED_MEDIA_UNAVAILABLE = -20,
		INSTALL_FAILED_VERIFICATION_TIMEOUT = -21,
		INSTALL_FAILED_VERIFICATION_FAILURE = -22,
		INSTALL_FAILED_PACKAGE_CHANGED = -23,
		INSTALL_FAILED_UID_CHANGED = -24,
		INSTALL_FAILED_VERSION_DOWNGRADE = -25,
		INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE = -26,
		INSTALL_PARSE_FAILED_NOT_APK = -100,
		INSTALL_PARSE_FAILED_BAD_MANIFEST = -101,
		INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION = -102,
		INSTALL_PARSE_FAILED_NO_CERTIFICATES = -103,
		INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES = -104,
		INSTALL_PARSE_FAILED_CERTIFICATE_ENCODING = -105,
		INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME = -106,
		INSTALL_PARSE_FAILED_BAD_SHARED_USER_ID = -107,
		INSTALL_PARSE_FAILED_MANIFEST_MALFORMED = -108,
		INSTALL_PARSE_FAILED_MANIFEST_EMPTY = -109,
		INSTALL_FAILED_INTERNAL_ERROR = -110,
		INSTALL_FAILED_USER_RESTRICTED = -111,
		INSTALL_FAILED_DUPLICATE_PERMISSION = -112,
		INSTALL_FAILED_NO_MATCHING_ABIS = -113,
		INSTALL_FAILED_ABORTED = -115,
		INSTALL_FAILED_EPHEMERAL_INVALID = -116,
		INSTALL_FAILED_INVALID_XAPK = -200,
		INSTALL_FAILED_EXPANSION_FILE_INVALID = -201,
		INSTALL_FAILED_EXPANSION_FILE_FAILED = -202,
		INSTALL_FAILED_APK_EXTRACTION_FAILED = -203,
		INSTALL_FAILED_INVALID_XAPK_VERSION = -204
	}
}


