using System;

namespace BlueStacks.Common
{
	public enum InstallerCodes
	{
		SUCCESS,
		INCOMPATIBLE_ARCHITECTURE_INSTALLER_STARTED = 0,
		LAUNCH_BLUESTACKS_ON_SUCCESSFUL_INSTALLATION = 2,
		INSTALLER_ALREADY_RUNNING = -1,
		INSTALLERPROPERTIES_INIT_FAILED = -2,
		VERSION_DOWNGRADE = -3,
		UPGRADE_NOT_SUPPORTED = -4,
		COMMON_UTILS_EXTRACT_FAILED = -5,
		CANCELLED_WHILE_UPGRADE = -6,
		CANCELLED_PRESERVE_KEYMAPPINGS = -7,
		DISALLOWED_CHARS_IN_DIR = -8,
		CANCELLED_WHILE_INSUFFICIENT_STORAGE = -9,
		OS_VERSION_NOT_SUPPORTED = -10,
		INSUFFICIENT_PHYSICALMEMORY = -11,
		GL_UNSUPPORTED = -12,
		REGISTRY_EDITING_DISABLED = -13,
		INSUFFICIENT_DISKSPACE = -14,
		BLUESTACKS_POSSIBLY_CORRUPT = -15,
		SERVICE_RUNNING_EXIT = -16,
		VTX_DISABLED = -17,
		HYPER_V_ENABLED = -18,
		SERVICE_MARKED_FOR_DELETION = -30,
		FAILED_CREATING_REGISTRY = -31,
		FAILED_TO_RESTORE_REGISTRY_DATA = -32,
		PROGRAM_FILES_ZIP_EXTRACT_FAILED = -33,
		PROGRAM_DATA_ZIP_EXTRACT_FAILED = -35,
		CLIENT_FILES_DEPLOY_FAILED = -36,
		CEF_DATA_DEPLOY_FAILED = -37,
		LOCALE_FILES_DEPLOY_FAILED = -38,
		ENGINE_FILES_DEPLOY_FAILED = -39,
		FAILED_TO_INSTALL_DRIVER = -40,
		FAILED_TO_CREATE_BSTKGLOBAL = -41,
		FAILED_TO_CREATE_VMCONFIG = -42,
		FAILED_TO_RESERVE_HTTP_PORTS = -43,
		OLD_DATA_DIR_DOESNT_EXIST = -44,
		FAILED_TO_RESTORE_CLIENT_DATA = -45,
		FAILED_TO_RESTORE_ANDROID_DATA = -46,
		FAILED_TO_MOVE_OLD_ITEMS = -49,
		FAILED_TO_RENAME_NEW_ITEMS = -51,
		ROLLBACK_FRESH_FAILED = -52,
		ROLLBACK_REGISTRY_FAILED = -53,
		ROLLBACK_PROGRAMFILES_FAILED = -54,
		ROLLBACK_PROGRAMDATA_FAILED = -55,
		UNHANDLED_EXCEPTION = -56,
		GAMEDATA_DEPLOY_FAILED = -57,
		ERROR_WHILE_UNINSTALLING_SERVICE = -58,
		UNABLE_TO_STOP_SERVICE_BEFORE_UNINSTALLING = -59,
		TEST_ROLLBACK = -255,
		TEST_ROLLBACK_FAIL = -256
	}
}


