using System;

namespace BlueStacks.Common
{
	public enum PartialUpdaterCodes
	{
		SUCCESS,
		LAUNCH_BLUESTACKS_ON_SUCCESS = 2,
		UPDATER_ALREADY_RUNNING = -1,
		FAILED_TO_CREATE_COPY = -10,
		FAILED_TO_DEPLOY_FILES = -11,
		FAILED_TO_CREATE_BACKUP = -12,
		FAILED_TO_RESTORE_FILES = -13,
		FAILED_TO_UPDATE_REGISTRY = -14,
		FAILED_TO_ROLLBACK_DIRS = -20,
		TEST_ROLLBACK = -255
	}
}


