using System;

namespace BlueStacks.Common
{
	public enum RegPropertyType
	{
		SPDRP_DEVICEDESC,
		SPDRP_HARDWAREID,
		SPDRP_COMPATIBLEIDS,
		SPDRP_UNUSED0,
		SPDRP_SERVICE,
		SPDRP_UNUSED1,
		SPDRP_UNUSED2,
		SPDRP_CLASS,
		SPDRP_CLASSGUID,
		SPDRP_DRIVER,
		SPDRP_CONFIGFLAGS,
		SPDRP_MFG,
		SPDRP_FRIENDLYNAME,
		SPDRP_LOCATION_INFORMATION,
		SPDRP_PHYSICAL_DEVICE_OBJECT_NAME,
		SPDRP_CAPABILITIES,
		SPDRP_UI_NUMBER,
		SPDRP_UPPERFILTERS,
		SPDRP_LOWERFILTERS,
		SPDRP_BUSTYPEGUID,
		SPDRP_LEGACYBUSTYPE,
		SPDRP_BUSNUMBER,
		SPDRP_ENUMERATOR_NAME,
		SPDRP_SECURITY,
		SPDRP_SECURITY_SDS,
		SPDRP_DEVTYPE,
		SPDRP_EXCLUSIVE,
		SPDRP_CHARACTERISTICS,
		SPDRP_ADDRESS,
		SPDRP_UI_NUMBER_DESC_FORMAT = 30,
		SPDRP_MAXIMUM_PROPERTY
	}
}


